import { db } from '@/db';
import { expenses } from '@/db/schema';

async function main() {
    const today = new Date();
    const threeMonthsAgo = new Date(today.getFullYear(), today.getMonth() - 3, today.getDate());
    
    const getRandomDate = () => {
        const start = threeMonthsAgo.getTime();
        const end = today.getTime();
        const randomTime = start + Math.random() * (end - start);
        const date = new Date(randomTime);
        return date.toISOString().split('T')[0];
    };

    const getRandomAmount = (min: number, max: number) => {
        return Math.round((min + Math.random() * (max - min)) * 100) / 100;
    };

    const sampleExpenses = [
        // Food expenses
        {
            userId: 1,
            amount: 67.45,
            category: 'Food',
            description: 'Grocery shopping at Whole Foods',
            date: getRandomDate(),
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            userId: 1,
            amount: 52.30,
            category: 'Food',
            description: 'Restaurant dinner at Italian bistro',
            date: getRandomDate(),
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            userId: 1,
            amount: 15.75,
            category: 'Food',
            description: 'Starbucks coffee and pastry',
            date: getRandomDate(),
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },
        {
            userId: 1,
            amount: 28.50,
            category: 'Food',
            description: 'Lunch at downtown cafe',
            date: getRandomDate(),
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-01-25').toISOString(),
        },
        {
            userId: 1,
            amount: 42.99,
            category: 'Food',
            description: 'Pizza delivery for family',
            date: getRandomDate(),
            createdAt: new Date('2024-02-02').toISOString(),
            updatedAt: new Date('2024-02-02').toISOString(),
        },
        {
            userId: 1,
            amount: 18.25,
            category: 'Food',
            description: 'Breakfast bagels and coffee',
            date: getRandomDate(),
            createdAt: new Date('2024-02-05').toISOString(),
            updatedAt: new Date('2024-02-05').toISOString(),
        },
        {
            userId: 1,
            amount: 38.80,
            category: 'Food',
            description: 'Chinese takeout dinner',
            date: getRandomDate(),
            createdAt: new Date('2024-02-10').toISOString(),
            updatedAt: new Date('2024-02-10').toISOString(),
        },
        {
            userId: 1,
            amount: 73.20,
            category: 'Food',
            description: 'Meal prep groceries at Trader Joes',
            date: getRandomDate(),
            createdAt: new Date('2024-02-15').toISOString(),
            updatedAt: new Date('2024-02-15').toISOString(),
        },
        {
            userId: 1,
            amount: 12.50,
            category: 'Food',
            description: 'Fast food lunch at McDonald\'s',
            date: getRandomDate(),
            createdAt: new Date('2024-02-20').toISOString(),
            updatedAt: new Date('2024-02-20').toISOString(),
        },
        {
            userId: 1,
            amount: 45.60,
            category: 'Food',
            description: 'Sushi restaurant dinner',
            date: getRandomDate(),
            createdAt: new Date('2024-03-01').toISOString(),
            updatedAt: new Date('2024-03-01').toISOString(),
        },

        // Transport expenses
        {
            userId: 1,
            amount: 18.50,
            category: 'Transport',
            description: 'Uber ride to work',
            date: getRandomDate(),
            createdAt: new Date('2024-01-16').toISOString(),
            updatedAt: new Date('2024-01-16').toISOString(),
        },
        {
            userId: 1,
            amount: 45.00,
            category: 'Transport',
            description: 'Gas fill-up at Shell station',
            date: getRandomDate(),
            createdAt: new Date('2024-01-22').toISOString(),
            updatedAt: new Date('2024-01-22').toISOString(),
        },
        {
            userId: 1,
            amount: 12.00,
            category: 'Transport',
            description: 'Downtown parking garage',
            date: getRandomDate(),
            createdAt: new Date('2024-01-28').toISOString(),
            updatedAt: new Date('2024-01-28').toISOString(),
        },
        {
            userId: 1,
            amount: 5.50,
            category: 'Transport',
            description: 'Bus ticket for commute',
            date: getRandomDate(),
            createdAt: new Date('2024-02-03').toISOString(),
            updatedAt: new Date('2024-02-03').toISOString(),
        },
        {
            userId: 1,
            amount: 32.75,
            category: 'Transport',
            description: 'Lyft ride to airport',
            date: getRandomDate(),
            createdAt: new Date('2024-02-08').toISOString(),
            updatedAt: new Date('2024-02-08').toISOString(),
        },
        {
            userId: 1,
            amount: 25.00,
            category: 'Transport',
            description: 'Monthly subway pass',
            date: getRandomDate(),
            createdAt: new Date('2024-02-12').toISOString(),
            updatedAt: new Date('2024-02-12').toISOString(),
        },
        {
            userId: 1,
            amount: 20.00,
            category: 'Transport',
            description: 'Car wash and vacuum',
            date: getRandomDate(),
            createdAt: new Date('2024-02-18').toISOString(),
            updatedAt: new Date('2024-02-18').toISOString(),
        },
        {
            userId: 1,
            amount: 8.50,
            category: 'Transport',
            description: 'Highway toll fees',
            date: getRandomDate(),
            createdAt: new Date('2024-03-05').toISOString(),
            updatedAt: new Date('2024-03-05').toISOString(),
        },

        // Entertainment expenses
        {
            userId: 1,
            amount: 32.00,
            category: 'Entertainment',
            description: 'Movie tickets for two',
            date: getRandomDate(),
            createdAt: new Date('2024-01-19').toISOString(),
            updatedAt: new Date('2024-01-19').toISOString(),
        },
        {
            userId: 1,
            amount: 85.50,
            category: 'Entertainment',
            description: 'Concert tickets at local venue',
            date: getRandomDate(),
            createdAt: new Date('2024-01-26').toISOString(),
            updatedAt: new Date('2024-01-26').toISOString(),
        },
        {
            userId: 1,
            amount: 15.99,
            category: 'Entertainment',
            description: 'Netflix premium subscription',
            date: getRandomDate(),
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-02-01').toISOString(),
        },
        {
            userId: 1,
            amount: 59.99,
            category: 'Entertainment',
            description: 'New video game purchase',
            date: getRandomDate(),
            createdAt: new Date('2024-02-07').toISOString(),
            updatedAt: new Date('2024-02-07').toISOString(),
        },
        {
            userId: 1,
            amount: 25.00,
            category: 'Entertainment',
            description: 'Museum admission tickets',
            date: getRandomDate(),
            createdAt: new Date('2024-02-14').toISOString(),
            updatedAt: new Date('2024-02-14').toISOString(),
        },
        {
            userId: 1,
            amount: 75.00,
            category: 'Entertainment',
            description: 'Theater show tickets',
            date: getRandomDate(),
            createdAt: new Date('2024-02-21').toISOString(),
            updatedAt: new Date('2024-02-21').toISOString(),
        },
        {
            userId: 1,
            amount: 12.99,
            category: 'Entertainment',
            description: 'Spotify premium subscription',
            date: getRandomDate(),
            createdAt: new Date('2024-03-02').toISOString(),
            updatedAt: new Date('2024-03-02').toISOString(),
        },
        {
            userId: 1,
            amount: 18.99,
            category: 'Entertainment',
            description: 'Gaming subscription service',
            date: getRandomDate(),
            createdAt: new Date('2024-03-08').toISOString(),
            updatedAt: new Date('2024-03-08').toISOString(),
        },

        // Shopping expenses
        {
            userId: 1,
            amount: 89.99,
            category: 'Shopping',
            description: 'New clothes at H&M',
            date: getRandomDate(),
            createdAt: new Date('2024-01-17').toISOString(),
            updatedAt: new Date('2024-01-17').toISOString(),
        },
        {
            userId: 1,
            amount: 145.50,
            category: 'Shopping',
            description: 'Electronics from Best Buy',
            date: getRandomDate(),
            createdAt: new Date('2024-01-24').toISOString(),
            updatedAt: new Date('2024-01-24').toISOString(),
        },
        {
            userId: 1,
            amount: 67.25,
            category: 'Shopping',
            description: 'Home decor items at Target',
            date: getRandomDate(),
            createdAt: new Date('2024-01-30').toISOString(),
            updatedAt: new Date('2024-01-30').toISOString(),
        },
        {
            userId: 1,
            amount: 120.00,
            category: 'Shopping',
            description: 'New running shoes at Nike store',
            date: getRandomDate(),
            createdAt: new Date('2024-02-06').toISOString(),
            updatedAt: new Date('2024-02-06').toISOString(),
        },
        {
            userId: 1,
            amount: 178.99,
            category: 'Shopping',
            description: 'Kitchen appliances on Amazon',
            date: getRandomDate(),
            createdAt: new Date('2024-02-13').toISOString(),
            updatedAt: new Date('2024-02-13').toISOString(),
        },
        {
            userId: 1,
            amount: 45.80,
            category: 'Shopping',
            description: 'Books at Barnes & Noble',
            date: getRandomDate(),
            createdAt: new Date('2024-02-19').toISOString(),
            updatedAt: new Date('2024-02-19').toISOString(),
        },
        {
            userId: 1,
            amount: 92.50,
            category: 'Shopping',
            description: 'Online shopping at Zara',
            date: getRandomDate(),
            createdAt: new Date('2024-02-25').toISOString(),
            updatedAt: new Date('2024-02-25').toISOString(),
        },
        {
            userId: 1,
            amount: 199.99,
            category: 'Shopping',
            description: 'New desk chair from IKEA',
            date: getRandomDate(),
            createdAt: new Date('2024-03-03').toISOString(),
            updatedAt: new Date('2024-03-03').toISOString(),
        },

        // Bills expenses
        {
            userId: 1,
            amount: 125.50,
            category: 'Bills',
            description: 'Monthly electric bill',
            date: getRandomDate(),
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            userId: 1,
            amount: 79.99,
            category: 'Bills',
            description: 'Internet service provider',
            date: getRandomDate(),
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },
        {
            userId: 1,
            amount: 65.00,
            category: 'Bills',
            description: 'Cell phone bill',
            date: getRandomDate(),
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-01-25').toISOString(),
        },
        {
            userId: 1,
            amount: 250.00,
            category: 'Bills',
            description: 'Rent portion for utilities',
            date: getRandomDate(),
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-02-01').toISOString(),
        },
        {
            userId: 1,
            amount: 55.25,
            category: 'Bills',
            description: 'Water and sewage bill',
            date: getRandomDate(),
            createdAt: new Date('2024-02-08').toISOString(),
            updatedAt: new Date('2024-02-08').toISOString(),
        },
        {
            userId: 1,
            amount: 89.99,
            category: 'Bills',
            description: 'Cable TV subscription',
            date: getRandomDate(),
            createdAt: new Date('2024-02-15').toISOString(),
            updatedAt: new Date('2024-02-15').toISOString(),
        },
        {
            userId: 1,
            amount: 150.00,
            category: 'Bills',
            description: 'Car insurance monthly payment',
            date: getRandomDate(),
            createdAt: new Date('2024-02-22').toISOString(),
            updatedAt: new Date('2024-02-22').toISOString(),
        },
        {
            userId: 1,
            amount: 180.00,
            category: 'Bills',
            description: 'HOA monthly fees',
            date: getRandomDate(),
            createdAt: new Date('2024-03-01').toISOString(),
            updatedAt: new Date('2024-03-01').toISOString(),
        },

        // Healthcare expenses
        {
            userId: 1,
            amount: 45.50,
            category: 'Healthcare',
            description: 'Pharmacy prescription refill',
            date: getRandomDate(),
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            userId: 1,
            amount: 75.00,
            category: 'Healthcare',
            description: 'Doctor visit copay',
            date: getRandomDate(),
            createdAt: new Date('2024-01-27').toISOString(),
            updatedAt: new Date('2024-01-27').toISOString(),
        },
        {
            userId: 1,
            amount: 89.99,
            category: 'Healthcare',
            description: 'Monthly gym membership',
            date: getRandomDate(),
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-02-01').toISOString(),
        },
        {
            userId: 1,
            amount: 120.00,
            category: 'Healthcare',
            description: 'Dental cleaning and checkup',
            date: getRandomDate(),
            createdAt: new Date('2024-02-09').toISOString(),
            updatedAt: new Date('2024-02-09').toISOString(),
        },
        {
            userId: 1,
            amount: 95.00,
            category: 'Healthcare',
            description: 'Annual vision exam',
            date: getRandomDate(),
            createdAt: new Date('2024-02-16').toISOString(),
            updatedAt: new Date('2024-02-16').toISOString(),
        },
        {
            userId: 1,
            amount: 65.00,
            category: 'Healthcare',
            description: 'Physical therapy session',
            date: getRandomDate(),
            createdAt: new Date('2024-02-23').toISOString(),
            updatedAt: new Date('2024-02-23').toISOString(),
        },
        {
            userId: 1,
            amount: 38.75,
            category: 'Healthcare',
            description: 'Vitamin and supplement purchase',
            date: getRandomDate(),
            createdAt: new Date('2024-03-04').toISOString(),
            updatedAt: new Date('2024-03-04').toISOString(),
        },

        // Education expenses
        {
            userId: 1,
            amount: 49.99,
            category: 'Education',
            description: 'Online course on Udemy',
            date: getRandomDate(),
            createdAt: new Date('2024-01-21').toISOString(),
            updatedAt: new Date('2024-01-21').toISOString(),
        },
        {
            userId: 1,
            amount: 85.50,
            category: 'Education',
            description: 'Programming books bundle',
            date: getRandomDate(),
            createdAt: new Date('2024-01-29').toISOString(),
            updatedAt: new Date('2024-01-29').toISOString(),
        },
        {
            userId: 1,
            amount: 35.25,
            category: 'Education',
            description: 'School supplies and stationery',
            date: getRandomDate(),
            createdAt: new Date('2024-02-04').toISOString(),
            updatedAt: new Date('2024-02-04').toISOString(),
        },
        {
            userId: 1,
            amount: 125.00,
            category: 'Education',
            description: 'Workshop registration fee',
            date: getRandomDate(),
            createdAt: new Date('2024-02-11').toISOString(),
            updatedAt: new Date('2024-02-11').toISOString(),
        },
        {
            userId: 1,
            amount: 180.00,
            category: 'Education',
            description: 'Professional certification exam',
            date: getRandomDate(),
            createdAt: new Date('2024-02-17').toISOString(),
            updatedAt: new Date('2024-02-17').toISOString(),
        },
        {
            userId: 1,
            amount: 95.00,
            category: 'Education',
            description: 'Professional training seminar',
            date: getRandomDate(),
            createdAt: new Date('2024-02-24').toISOString(),
            updatedAt: new Date('2024-02-24').toISOString(),
        },
        {
            userId: 1,
            amount: 29.99,
            category: 'Education',
            description: 'Language learning app subscription',
            date: getRandomDate(),
            createdAt: new Date('2024-03-06').toISOString(),
            updatedAt: new Date('2024-03-06').toISOString(),
        },

        // Other expenses
        {
            userId: 1,
            amount: 55.00,
            category: 'Other',
            description: 'Birthday gift for friend',
            date: getRandomDate(),
            createdAt: new Date('2024-01-23').toISOString(),
            updatedAt: new Date('2024-01-23').toISOString(),
        },
        {
            userId: 1,
            amount: 75.00,
            category: 'Other',
            description: 'Charity donation to local shelter',
            date: getRandomDate(),
            createdAt: new Date('2024-01-31').toISOString(),
            updatedAt: new Date('2024-01-31').toISOString(),
        },
        {
            userId: 1,
            amount: 42.50,
            category: 'Other',
            description: 'Pet supplies and food',
            date: getRandomDate(),
            createdAt: new Date('2024-02-05').toISOString(),
            updatedAt: new Date('2024-02-05').toISOString(),
        },
        {
            userId: 1,
            amount: 95.00,
            category: 'Other',
            description: 'Home repair materials',
            date: getRandomDate(),
            createdAt: new Date('2024-02-12').toISOString(),
            updatedAt: new Date('2024-02-12').toISOString(),
        },
        {
            userId: 1,
            amount: 38.25,
            category: 'Other',
            description: 'Garden tools and supplies',
            date: getRandomDate(),
            createdAt: new Date('2024-02-19').toISOString(),
            updatedAt: new Date('2024-02-19').toISOString(),
        },
        {
            userId: 1,
            amount: 28.50,
            category: 'Other',
            description: 'Miscellaneous household items',
            date: getRandomDate(),
            createdAt: new Date('2024-02-26').toISOString(),
            updatedAt: new Date('2024-02-26').toISOString(),
        },
        {
            userId: 1,
            amount: 62.99,
            category: 'Other',
            description: 'Holiday decorations purchase',
            date: getRandomDate(),
            createdAt: new Date('2024-03-07').toISOString(),
            updatedAt: new Date('2024-03-07').toISOString(),
        },
    ];

    await db.insert(expenses).values(sampleExpenses);
    
    console.log(`✅ Expenses seeder completed successfully - ${sampleExpenses.length} records inserted`);
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});